### ISSUE TITLE
mscTesting don't run as expected

### ISSUE THREAD

**Issue by BOBILLIER** [wwatson4506/UsbMscFat#8]
have test MSCDriveinfo on my t3.6 and all run correctly and I read correctly my USB Stick Infos. But I have tried another example "mscTesting" how is delivered with USBHost_t36 library and write by WWatson, and this doesn't detect my USB stick and return error code 35 at the start. But after seconds, I saw it when I send a character to Serial port. I know that this example is not a part of this library but a part of USBHost_t36 library, but I think it will be good you correct this or ask to Teensyduino to remove it to avoid misunderstanding.

**Comment by wwatson4506** [comment]
BOBILLIER,
Code 35 means that MSC timed out waiting for the USB device to come online.
I have a pull request in for that for USBHost_t36. Right now you can change
two values in the msc.h file and retry to connect the the same device that
failed. The msc.h file is located in the utility folder in the USBHost_t36
library. Starting at line #73 find these lines:

// These two defines are timeouts for detecting a connected drive
// and waiting for it to be operational.
#define MEDIA_READY_TIMEOUT 1000
#define MSC_CONNECT_TIMEOUT 4000

And change them to:

// These two defines are timeouts for detecting a connected drive
// and waiting for it to be operational.
#define MEDIA_READY_TIMEOUT 5000
#define MSC_CONNECT_TIMEOUT 5000

Another user as well as myself was having the same problem when trying to
use a USB SD card reader. Giving a longer timeout fixed the problem.
Note: Some USB devices can take up to a minute or more to become ready. USB
hard drives in particular.

Because of FatFS and uSDFS still being used I do not want to eliminate
mscTesting.

**Comment by BOBILLIER** [comment]
You are right. In my case (and my USB Stick) MSC.begin take up to 6 seconds.
