### ISSUE TITLE
Why msDriveInfo.mounted always return 0 ?

### ISSUE THREAD

**Issue by BOBILLIER** [wwatson4506/UsbMscFat#9]
I have played with your library and want to test if there is a mount-unmount mechanism, but don't really found it.
I just found msDriveInfo.mounted property, but in my test, before or after operation write in file opération, the mount stay always to 0. I want to play with this because, in my project, I need to start USB, write some datas, and sometimes, unplug USB Stick to get them, plug the USB stick again, and record some datas again. And I need a clean "unmount" "mount" operation. For the moment my operation is to lock write operation, unplug and when I plug again I proceed one  MSC.begin again and free record operation. That's run, but I'm not sure that it's a good thing, and If I will do that a lot that impacts memory allocation. Do know what is good way to do that? 
Thanks

**Comment by wwatson4506** [comment]
BOBILLIER,
Now that we are using SdFat instead of FatFs there is no real mount or
ummount. The nice thing about SdFat is that it does not use any memory
allocation like malloc. so you won't see an impact on memory. If I
understand right it is done at compile time. As far as hot plugging just
make sure that you close any open files before you remove any USB drive, It
does not hurt to flush or sync any open file  before you close them. You
can call MSC.begin as many times as needed without problems. Calling begin
is pretty much the same as mounting a USB drive😀

**Comment by BOBILLIER** [comment]
Ok Nice to know that. I will just need to test that the file is close before unplugging the USB stick.
